### ISSUE TITLE
 Create View Gameboard Join Game

### ISSUE THREAD

**Issue by brelane33** [peter-banfield/its-not-trivial#7]
Create a view to join a game and display room code

**Comment by peter-banfield** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create View Gameboard Join Game](https://trello.com/c/pcHCAtRf/29-create-view-gameboard-join-game)

**Comment by peter-banfield** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create View gameboard room creation](https://trello.com/c/yMNlmoA8/28-create-view-gameboard-room-creation)
